###################################
# Airflow - Common Configs
###################################
airflow:

 # image:
 #   repository: fondahub/airflow
 #   tag: 2.0.0
 #   pullPolicy: IfNotPresent
 #   pullSecret: ""

  executor: CeleryExecutor

  image:
    repository: fondahub/airflow
    tag: 2.0.0
    pullPolicy: Always
    pullSecret: ""  


  config:
    AIRFLOW__KUBERNETES__DAGS_IN_IMAGE: "True"
    #AIRFLOW__LOGGING__REMOTE_LOGGING: "True"
    #AIRFLOW__LOGGING__REMOTE_BASE_LOG_FOLDER: "/opt/airflow/logs"
    AIRFLOW__WEBSERVER__RBAC: "False"
    AIRFLOW__API__AUTH_BACKEND: "airflow.api.auth.backend.deny_all"
    #AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID: "google_cloud_default"

  extraVolumeMounts: # this will get the volume and mount it to that path in the container
    - name: dags
      mountPath: /opt/airflow/dags  # location in the container it will put the directory mentioned below.
    - name: logs
      mountPath: /opt/airflow/logs

  extraVolumes: # this will create the volume from the directory
    - name: dags
      hostPath:
        path: "/airflow/dags"
    - name: logs
      hostPath:
        path: "/airflow/logs"

scheduler:
  extraInitContainers:
  - name: volume-logs
    image: busybox
    command: ["sh", "-c", "chown -R 50000:50000 /opt/airflow/logs/"]
    volumeMounts:
      - mountPath: /opt/airflow/logs/
        name: logs

web:                                                                                                                                                                                                        
  service:                                                                                                                                                                                                  
    type: NodePort                                                                                                                                                                                          
    nodePort:                                                                                                                                                                                               
      http: "30876"
###################################
# Airflow - DAGs Configs
###################################
dags:
  ## the airflow dags folder
  ##
  path: /opt/airflow/dags
  doNotPickle: false
  installRequirements: false

  ## configs for the dags PVC
  ##
  persistence:
    enabled: false
    existingClaim: ""
    subPath: ""
    storageClass: ""
    accessMode: ReadOnlyMany
    size: 1Gi

  ## configs for the DAG git repository & sync container
  ##
  git:
    url: ""

    ## the branch/tag/sha1 which we clone
    ##
    ref: master
    secret: ""
    sshKeyscan: false
    privateKeyName: id_rsa
    repoHost: ""
    repoPort: 22
    gitSync:
      ## enable the git-sync sidecar container
      ##
      enabled: false
      resources: {}

      ## the docker image for the git-sync container
      image:
        repository: alpine/git
        tag: latest
        ## values: Always or IfNotPresent
        pullPolicy: Always

      ## the git sync interval in seconds
      ##
      refreshTime: 60

  ## configs for the git-clone container
  ##
  ## NOTE:
  ## - use this container if you want to only clone the external git repo
  ##   at Pod start-time, and not keep it synchronised afterwards
  ##
  initContainer:
    ## enable the git-clone sidecar container
    ##
    ## NOTE:
    ## - this is NOT required for the git-sync sidecar to work
    ## - this is mostly used for when `dags.installRequirements` is true to ensure that
    ##   requirements.txt is available at Pod start
    ##
    enabled: false

    ## resource requests/limits for the git-clone container
    ##
    ## EXAMPLE:
    ##   resources:
    ##     requests:
    ##       cpu: "50m"
    ##       memory: "64Mi"
    ##
    resources: {}

    ## the docker image for the git-clone container
    image:
      repository: alpine/git
      tag: latest
      ## values: Always or IfNotPresent
      pullPolicy: Always

    ## path to mount dags-data volume to
    ##
    ## WARNING:
    ## - this path is also used by the git-sync container
    ##
    mountPath: "/dags"

    ## sub-path under `dags.initContainer.mountPath` to sync dags to
    ##
    ## WARNING:
    ## - this path is also used by the git-sync container
    ## - this MUST INCLUDE the leading /
    ##
    ## EXAMPLE:
    ##   syncSubPath: "/subdirWithDags"
    ##
    syncSubPath: ""
