---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
networking:
  apiServerAddress: 0.0.0.0
  apiServerPort: 19090
nodes:
  - role: control-plane
    extraMounts:
    - hostPath: REPO_PATH/dags
      containerPath: /airflow/dags
    - hostPath: REPO_PATH/data
      containerPath: /data
    - hostPath: REPO_PATH/logs
      containerPath: /airflow/logs
    extraPortMappings:
    - containerPort: 30876
      hostPort: 8888
      
  - role: worker
    extraMounts:
    - hostPath: REPO_PATH/dags
      containerPath: /airflow/dags
    - hostPath: REPO_PATH/data
      containerPath: /data
    - hostPath: REPO_PATH/logs
      containerPath: /airflow/logs
    
