
apiVersion: v1
kind: Pod
metadata:
  name: observe-fonda-datasets
  namespace: default
spec:
  containers:
  - name: test
    image: davidfrantz/force:3.6.5
    command: ["sleep", "1000000"]
    securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 0
    volumeMounts:
    - name: fonda-datasets-mount
      mountPath: /data
  restartPolicy: Never
  volumes:
  - name: fonda-datasets-mount
    persistentVolumeClaim:
      claimName: fonda-datasets
