apiVersion: v1
kind: PersistentVolume
metadata:
  name: force-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/airflow-data"

