apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: force-pvc
  namespace: airflow
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi

