kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: airflow-service-admin
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["services", "pods", "nodes"]
  verbs: ["get", "watch", "list", "create"]
