apiVersion: v1
kind: Pod
metadata:
  name: test-force
spec:
  containers:
  - name: test
    image: davidfrantz/force
    command: ["sleep", "1000000"]
    securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 0
    volumeMounts:
    - name: force-pv
      mountPath: /data
    - name: test-volume
      mountPath: /host-local
  restartPolicy: Never
  volumes:
  - name: force-pv
    persistentVolumeClaim:
      claimName: force-pvc
  - name: test-volume
    hostPath:
      path: /data
      type: Directory


