apiVersion: v1
kind: Pod
metadata:
  name: test-force
  namespace: default
spec:
  containers:
  - name: test
    image: davidfrantz/force:3.6.5
    command: ["sleep", "1000000"]
    securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 0
    volumeMounts:
    - name: fonda-datasets
      mountPath: /data/input
    - name: force-airflow
      mountPath: /data/outputs
  restartPolicy: Never
  volumes:
  - name: fonda-datasets
    persistentVolumeClaim:
      claimName: fonda-datasets
  - name: force-airflow
    persistentVolumeClaim:
      claimName: force-airflow

