apiVersion: v1
kind: Pod
metadata:
  name: test-force
spec:
  containers:
  - name: test
    image: davidfrantz/force
    command: ["sleep", "1000000"]
    securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 0
    volumeMounts:
    - name: force-pv
      mountPath: /data
  restartPolicy: Never
  volumes:
  - name: force-pv
    persistentVolumeClaim:
      claimName: force-pvc


