apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: test
    image: bash
    command: ["sleep", "10000"]
    volumeMounts:
    - name: force-pv
      mountPath: /data
  restartPolicy: Never
  volumes:
  - name: force-pv
    persistentVolumeClaim:
      claimName: force-pvc


